In [1]:
import pandas as pd
import math

df = pd.read_csv("../src/results_raw_table_2/table2_nogrid_100.csv", header= None)

In [2]:
# taken from t table given num of samples and desired confidence
t_distribuation = 1.984 
num_of_samples = 100

In [3]:
df_sparse = df


data = []
for model in df_sparse[0].unique():
    
    row = [model]
    for dataset in df_sparse[1].unique():
        mean_acc = df_sparse[(df_sparse[0]==model) & (df_sparse[1]==dataset)][7]
        std = df_sparse[(df_sparse[0]==model) & (df_sparse[1]==dataset)][8]
        std_error = std / math.sqrt(num_of_samples)
        ci = std_error * t_distribuation

        row.append(mean_acc.values[0].round(2).astype(str) + " + " + ci.values[0].round(2).astype(str))
    data.append(row)
    row = []

table_sparse = pd.DataFrame(data, columns= ["model", 'cora', 'citeseer', 'pubmed', 'computers', 'photo', 'chameleon', 'film', 'squirrel',
 'texas', 'cornell'])

In [4]:
print(table_sparse.to_latex(index=False))
table_sparse

\begin{tabular}{lllllllllll}
\toprule
  model &         cora &     citeseer &       pubmed &    computers &        photo &    chameleon &         film &     squirrel &        texas &      cornell \\
\midrule
    SGC & 74.58 + 0.35 & 68.02 + 0.22 & 77.81 + 0.24 & 62.23 + 0.58 & 65.05 + 0.76 & 42.34 + 0.67 & 29.97 + 0.16 & 30.84 + 0.43 & 61.15 + 1.29 &  41.8 + 0.98 \\
    MLP &  49.49 + 0.5 & 51.52 + 0.58 &  80.3 + 0.13 & 66.98 + 0.33 & 75.66 + 0.38 &  48.12 + 0.4 & 39.18 + 0.16 & 29.56 + 0.35 & 82.95 + 0.77 & 87.54 + 0.72 \\
  APPNP & 79.37 + 0.32 & 68.33 + 0.34 & 83.76 + 0.09 & 67.45 + 0.51 & 84.47 + 0.44 & 39.23 + 0.74 & 33.58 + 0.24 & 21.65 + 0.22 & 13.93 + 1.79 & 20.82 + 4.32 \\
ChebNet & 70.66 + 0.46 & 64.28 + 0.39 & 83.75 + 0.06 &  79.05 + 0.3 & 87.35 + 0.24 & 57.79 + 0.47 &  37.7 + 0.19 &  36.18 + 0.3 & 81.31 + 0.73 &  76.89 + 1.2 \\
  JKNet &  72.69 + 0.7 & 60.01 + 0.89 & 82.71 + 0.11 & 50.31 + 2.09 & 73.94 + 2.09 & 51.53 + 0.42 & 27.62 + 0.27 & 37.82 + 0.26 & 66.23 + 3.63 & 45.57 + 3.24 \\
    GCN & 75.02 + 0.23 & 67.31 + 0.37 & 83.83 + 0.09 & 69.89 + 0.62 & 81.16 + 0.65 & 58.73 + 0.36 & 30.56 + 0.18 &  34.97 + 0.3 & 66.89 + 1.11 & 57.54 + 1.34 \\
    GAT &   77.3 + 0.3 & 67.16 + 0.48 & 83.18 + 0.09 &  66.4 + 1.22 & 80.99 + 0.69 & 55.43 + 0.43 & 32.56 + 0.42 & 25.52 + 0.32 & 73.77 + 1.08 & 74.26 + 0.92 \\
 GPRGNN & 75.59 + 0.23 & 62.37 + 0.31 & 83.01 + 0.07 & 81.32 + 0.63 & 89.81 + 0.21 & 60.57 + 0.52 & 31.84 + 0.29 & 41.37 + 0.37 & 84.43 + 1.07 & 79.67 + 1.27 \\
\bottomrule
\end{tabular}

/tmp/ipykernel_1217/199789607.py:1: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(table_sparse.to_latex(index=False))

,model,cora,citeseer,pubmed,computers,photo,chameleon,film,squirrel,texas,cornell
0,SGC,74.58 + 0.35,68.02 + 0.22,77.81 + 0.24,62.23 + 0.58,65.05 + 0.76,42.34 + 0.67,29.97 + 0.16,30.84 + 0.43,61.15 + 1.29,41.8 + 0.98
1,MLP,49.49 + 0.5,51.52 + 0.58,80.3 + 0.13,66.98 + 0.33,75.66 + 0.38,48.12 + 0.4,39.18 + 0.16,29.56 + 0.35,82.95 + 0.77,87.54 + 0.72
2,APPNP,79.37 + 0.32,68.33 + 0.34,83.76 + 0.09,67.45 + 0.51,84.47 + 0.44,39.23 + 0.74,33.58 + 0.24,21.65 + 0.22,13.93 + 1.79,20.82 + 4.32
3,ChebNet,70.66 + 0.46,64.28 + 0.39,83.75 + 0.06,79.05 + 0.3,87.35 + 0.24,57.79 + 0.47,37.7 + 0.19,36.18 + 0.3,81.31 + 0.73,76.89 + 1.2
4,JKNet,72.69 + 0.7,60.01 + 0.89,82.71 + 0.11,50.31 + 2.09,73.94 + 2.09,51.53 + 0.42,27.62 + 0.27,37.82 + 0.26,66.23 + 3.63,45.57 + 3.24
5,GCN,75.02 + 0.23,67.31 + 0.37,83.83 + 0.09,69.89 + 0.62,81.16 + 0.65,58.73 + 0.36,30.56 + 0.18,34.97 + 0.3,66.89 + 1.11,57.54 + 1.34
6,GAT,77.3 + 0.3,67.16 + 0.48,83.18 + 0.09,66.4 + 1.22,80.99 + 0.69,55.43 + 0.43,32.56 + 0.42,25.52 + 0.32,73.77 + 1.08,74.26 + 0.92
7,GPRGNN,75.59 + 0.23,62.37 + 0.31,83.01 + 0.07,81.32 + 0.63,89.81 + 0.21,60.57 + 0.52,31.84 + 0.29,41.37 + 0.37,84.43 + 1.07,79.67 + 1.27

In [5]:
phi_dfs = []
phis = [-1.0, -0.75, -0.5, -0.25, 0, 0.25, 0.5, 0.75, 1]
for phi in phis:
    phi_csv = pd.read_csv(f"../src/results_raw_cSBM/cSBM_data_phi_{phi}.csv", header=None)
    phi_dfs.append(phi_csv)

combined = pd.concat(phi_dfs, axis=0)

In [6]:
def generate_table(df_input):
    data = []
    for model in df_input[0].unique():
        
        row = [model]
        for dataset in df_input[1].unique():
            mean_acc = df_input[(df_input[0]==model) & (df_input[1]==dataset)][7]
            std = df_input[(df_input[0]==model) & (df_input[1]==dataset)][8]
            std_error = std / math.sqrt(num_of_samples)
            ci = std_error * t_distribuation

            row.append(mean_acc.values[0].round(2).astype(str) + " + " + ci.values[0].round(2).astype(str))

        data.append(row)
        row = []

    return pd.DataFrame(data, columns= ["model", '-1', '-0.75', '-0.5', '-0.25', '0', '0.25', '0.5', '0.75',
    '1'])

In [7]:
df_dense = combined[combined[2]==0.6]
table_dense = generate_table(df_dense)

print(table_dense.to_latex(index=False))
table_dense.to_csv("cSBM_dense.csv")

\begin{tabular}{llllllllll}
\toprule
  model &           -1 &        -0.75 &         -0.5 &        -0.25 &            0 &         0.25 &          0.5 &         0.75 &            1 \\
\midrule
    SGC & 69.68 + 0.29 & 78.52 + 0.34 & 71.05 + 0.21 & 59.34 + 0.25 & 63.95 + 0.27 & 81.46 + 0.24 & 93.82 + 0.18 & 97.42 + 0.14 & 94.26 + 0.08 \\
    MLP & 50.23 + 0.28 & 67.87 + 0.28 & 75.83 + 0.32 & 79.71 + 0.23 &  82.35 + 0.2 & 80.63 + 0.25 &  76.64 + 0.2 & 68.03 + 0.28 &  49.5 + 0.16 \\
  JKNet & 86.75 + 0.76 & 89.97 + 1.14 &  84.91 + 0.6 & 51.81 + 0.52 &   59.6 + 0.4 &  77.61 + 0.3 & 92.56 + 0.12 & 97.97 + 0.06 & 98.26 + 0.07 \\
  APPNP &  48.8 + 0.12 & 49.36 + 0.12 &  49.31 + 0.2 & 60.63 + 0.32 & 75.12 + 0.27 & 85.78 + 0.16 &  94.25 + 0.1 & 97.97 + 0.09 & 96.93 + 0.09 \\
 GPRGNN & 98.29 + 0.06 & 97.44 + 0.09 & 92.94 + 0.16 & 81.17 + 0.21 & 73.94 + 0.17 & 80.85 + 0.14 & 92.07 + 0.17 &  97.69 + 0.1 & 98.58 + 0.06 \\
    GCN & 78.75 + 0.27 & 83.88 + 0.26 & 76.86 + 0.34 & 59.41 + 0.27 & 62.78 + 0.29 & 80.73 + 0.22 &  93.7 + 0.13 & 97.48 + 0.09 & 96.63 + 0.13 \\
    GAT & 87.29 + 0.25 & 87.62 + 0.33 & 76.93 + 0.25 & 58.65 + 0.36 &  62.4 + 0.21 & 79.83 + 0.26 & 92.83 + 0.18 & 97.78 + 0.05 & 98.31 + 0.08 \\
ChebNet &  90.05 + 0.2 & 95.19 + 0.15 & 91.97 + 0.17 & 84.24 + 0.26 & 80.01 + 0.27 & 84.88 + 0.17 & 92.01 + 0.14 & 94.72 + 0.15 & 88.25 + 0.26 \\
\bottomrule
\end{tabular}

/tmp/ipykernel_1217/3463055756.py:4: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(table_dense.to_latex(index=False))

In [8]:
df_sparse = combined[combined[2]==0.025]
table_dense = generate_table(df_dense)

print(table_dense.to_latex(index=False))
table_dense.to_csv("../data/cSBM_sparse.csv")

\begin{tabular}{llllllllll}
\toprule
  model &           -1 &        -0.75 &         -0.5 &        -0.25 &            0 &         0.25 &          0.5 &         0.75 &            1 \\
\midrule
    SGC & 55.24 + 0.54 & 60.57 + 0.44 & 56.23 + 0.49 &  51.85 + 0.2 & 54.19 + 0.36 & 67.72 + 0.18 & 85.15 + 0.15 & 90.63 + 0.13 & 75.96 + 0.24 \\
    MLP & 50.17 + 0.11 & 54.15 + 0.36 & 58.16 + 0.19 & 61.04 + 0.21 &  63.2 + 0.21 & 61.51 + 0.19 & 58.96 + 0.26 & 53.98 + 0.46 & 49.61 + 0.11 \\
  JKNet & 50.83 + 0.27 & 51.88 + 0.52 & 50.43 + 0.12 & 50.12 + 0.09 & 53.04 + 0.32 & 65.67 + 0.31 & 86.17 + 0.14 & 94.72 + 0.07 &  89.4 + 0.11 \\
  APPNP & 49.61 + 0.07 & 49.72 + 0.06 & 49.89 + 0.08 & 51.73 + 0.23 & 57.52 + 0.52 & 68.72 + 0.29 & 85.14 + 0.14 & 94.24 + 0.09 & 88.47 + 0.24 \\
 GPRGNN & 49.18 + 0.09 & 49.54 + 0.09 & 50.03 + 0.08 & 51.69 + 0.15 & 55.69 + 0.16 & 65.71 + 0.26 & 84.85 + 0.19 &   94.8 + 0.1 & 91.05 + 0.17 \\
    GCN & 56.34 + 0.15 &  61.52 + 0.1 & 55.96 + 0.43 &  52.6 + 0.19 & 53.79 + 0.41 & 66.93 + 0.33 &  84.4 + 0.21 & 89.96 + 0.14 &  76.8 + 0.27 \\
    GAT & 57.58 + 0.17 & 61.32 + 0.21 &  56.97 + 0.2 & 52.97 + 0.13 & 54.81 + 0.26 & 66.26 + 0.18 & 83.09 + 0.15 & 89.24 + 0.21 & 78.34 + 0.18 \\
ChebNet & 63.52 + 0.43 & 70.73 + 0.62 & 71.13 + 0.37 & 62.66 + 0.36 & 60.22 + 0.39 &  64.85 + 0.7 & 71.83 + 0.43 & 71.86 + 0.69 & 60.11 + 0.35 \\
\bottomrule
\end{tabular}

/tmp/ipykernel_1217/1273088750.py:4: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(table_dense.to_latex(index=False))